name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
      - dev
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        modules: ["@Sauce"]
    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: install dependencies
        run: |
          cd uiAutomation
          cpm ci

      - name: run tests
        run: |
          cd uiAutomation
          npx playwright test --grep {{matrix.modules}}

      - name: upload playwright report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: uiAutomation/playwright-report

  # push-to-dockerhub:
  #   needs: build
  #   if: github.ref == 'refs/heads/dev' && github.event_name == 'push' && job.status == 'success'
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: checkout dev branch
  #       uses: actions/checkout@v3
  #     - name: rebuild image then push to docker hub
  #       uses: docker/build-push-actions@v3

  # nightly:
  #   runs-on: ubuntu-20.04
  #   if: github.refs == 'refs/heads/dev'
  #   strategy:
  #     matrix:
  #       modules: ["@Sauce"]
  #   steps:
  #     - name: checkout closed
  #       uses: actions/checkout@v3
  #     - name: nightly run
  #       run: |
  #         cd uiAutomation
  #         npx playwright test --grep ${{matrix.modules}}
  #     - name: upload actions/upload-artifact
  #       uses: actions/upload-artifact
  #       with:
  #         -name: playwight-report
  #         path: uiAutomation/playwright-report
